import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import "./globals.css";

const Jersey = Jersey_15({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Jersey.className}>{children}</body>
    </html>
  );
}
